# Generated by Django 5.0.11 on 2025-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_adress_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='secondName',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
