# Generated by Django 5.0.11 on 2025-01-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_secondname_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='secondName',
            new_name='second_name',
        ),
    ]
