# Generated by Django 5.0.11 on 2025-01-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_secondname_customer_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=True),
        ),
    ]
